# Configuration des notifications CI/CD
# Ce fichier peut être utilisé pour configurer les notifications Slack, email, etc.

notifications:
  # Notifications Slack
  slack:
    enabled: false
    webhook_url: "YOUR_SLACK_WEBHOOK_URL"
    channel: "#android-deployments"
    username: "Firebase Bot"
    icon_emoji: ":fire:"
    
  # Notifications Email
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "your-email@gmail.com"
    password: "YOUR_APP_PASSWORD"
    recipients:
      - "team@yourcompany.com"
      - "qa@yourcompany.com"
      
  # Notifications Discord
  discord:
    enabled: false
    webhook_url: "YOUR_DISCORD_WEBHOOK_URL"
    username: "Firebase Deploy Bot"
    
  # Notifications Teams
  teams:
    enabled: false
    webhook_url: "YOUR_TEAMS_WEBHOOK_URL"
    
  # Configuration des événements
  events:
    on_success: true
    on_failure: true
    on_start: false
    
  # Messages personnalisés
  messages:
    success:
      title: "✅ Déploiement réussi"
      color: "good"
      text: "L'APK {build_type} a été déployé avec succès vers Firebase App Distribution"
      
    failure:
      title: "❌ Déploiement échoué"
      color: "danger"
      text: "Le déploiement de l'APK {build_type} a échoué. Vérifiez les logs pour plus de détails."
      
    start:
      title: "🚀 Déploiement en cours"
      color: "warning"
      text: "Déploiement de l'APK {build_type} en cours..."

# Configuration des environnements
environments:
  development:
    name: "Development"
    color: "blue"
    icon: ":construction:"
    
  staging:
    name: "Staging"
    color: "yellow"
    icon: ":warning:"
    
  production:
    name: "Production"
    color: "red"
    icon: ":rocket:"

# Configuration des métriques
metrics:
  enabled: true
  collect:
    - build_time
    - deploy_time
    - apk_size
    - success_rate
    
  thresholds:
    build_time_warning: 300  # 5 minutes
    build_time_error: 600    # 10 minutes
    deploy_time_warning: 120 # 2 minutes
    deploy_time_error: 300   # 5 minutes
